### ISSUE TITLE
Botania: Server crash when attempting to use Cacophonium on a note block

### ISSUE THREAD

**Issue by kingofrunes** [asiekierka/CharsetMC#104]
When attempting to use cacophonium on a note block from Botania the following crash is generated:

java.lang.NoSuchMethodError: net.minecraft.util.SoundEvent.func_187503_a()Lnet/minecraft/util/ResourceLocation;
at pl.asie.charset.audio.note.NoteBlockManager.onNoteEvent(NoteBlockManager.java:67)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_427_NoteBlockManager_onNoteEvent_Play.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
at net.minecraft.block.BlockNote.func_189539_a(BlockNote.java:111)
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:458)
at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:1231)
at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1218)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:233)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
at java.lang.Thread.run(Unknown Source)

**Comment by asiekierka** [comment]
Is the version of Charset you're using 0.3.1 or higher?

**Comment by kingofrunes** [comment]
Come to think of it, I think that's the problem. I thought what was on curseforge was the latest. Looks like that hasn't been updated in ages. Could you point me in the location of the most recent version of charset please and thank you? Then you can go ahead and close this.

This is with Charset-0.3.0-pre15

**Comment by kingofrunes** [comment]
nevermind found it, closing

**Comment by asiekierka** [comment]
http://charset.asie.pl/ for future reference. I do not use CurseForge, although Vazkii did for a while when he was maintaining the mod.
