### ISSUE TITLE
[Minor] Recipe types not registered

### ISSUE THREAD

**Issue by sargunv** [asiekierka/CharsetMC#110]
Just a minor issue: Forge says that Charset's recipe types haven't been registered, which causes the recipe sorter to complain in the log during load. I get this error log three times, with `ModCharsetStorage$2` replaced with `ModCharsetStorage$3` and `ModCharsetStorage$4`.

I'm currently on 0.4.0-pre6.

```
[18:38:58] [Client thread/WARN] [FML]: ****************************************
[18:38:58] [Client thread/WARN] [FML]: * Unknown recipe class! pl.asie.charset.storage.ModCharsetStorage$2 Modders need to register their recipe types with net.minecraftforge.oredict.RecipeSorter
[18:38:58] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.getPriority(RecipeSorter.java:237)
[18:38:58] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:172)
[18:38:58] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:52)
[18:38:58] [Client thread/WARN] [FML]: *  at java.util.TimSort.binarySort(TimSort.java:296)
[18:38:58] [Client thread/WARN] [FML]: *  at java.util.TimSort.sort(TimSort.java:239)
[18:38:58] [Client thread/WARN] [FML]: *  at java.util.Arrays.sort(Arrays.java:1512)...
[18:38:58] [Client thread/WARN] [FML]: ****************************************
```

**Comment by asiekierka** [comment]
Fixed somewhere between 0.4.0-pre10 and 0.4.0.
