### ISSUE TITLE
Crash when rendering pipe with a blockless? fluid

### ISSUE THREAD

**Issue by codewarrior0** [asiekierka/CharsetMC#119]
... that apparently doesn't exist in block form? ImmEng Creosote, in this example.

```
java.lang.NullPointerException: Rendering Block Entity
	at pl.asie.charset.pipes.pipe.SpecialRendererPipe.renderMultipartFast(SpecialRendererPipe.java:264)
	at pl.asie.charset.pipes.pipe.SpecialRendererPipe.renderMultipartFast(SpecialRendererPipe.java:52)

Charset-mc1.10.2-0.3.2-b6c6110f0942700e.jar
ImmersiveEngineering-0.10-55.jar
```

**Comment by codewarrior0** [comment]
May be related to https://github.com/CharsetMC/Charset/issues/113#issuecomment-274353604 :wink:

**Comment by asiekierka** [comment]
Please try updating Charset to the latest version first.

**Comment by codewarrior0** [comment]
Same crash in b210fb68b46f2eb18c7703b89d474968313ae01a

```
java.lang.NullPointerException: Rendering Block Entity
        at pl.asie.charset.pipes.pipe.SpecialRendererPipe.renderMultipartFast(SpecialRendererPipe.java:263)
        at pl.asie.charset.pipes.pipe.SpecialRendererPipe.renderMultipartFast(SpecialRendererPipe.java:52)
        at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerFast(MultipartContainerSpecialRenderer.java:105)
```

**Comment by codewarrior0** [comment]
I managed to quick-fix it by passing DEFAULT_STATE instead of the fluid-block-derived state, but now the extra quads in the pipe's fluid are bugging me.

**Comment by asiekierka** [comment]
The extra quads aren't going to go away without a rewrite of the rendering system for fluids, and that's not happening on 1.10.2 because the 1.10.2 fluid pipe implementation is a bit of a joke.
