### ISSUE TITLE
java.util.concurrent.ExecutionException: (1.11.2-2227)(Charset-mc1.11.2-0.4.0-pre10-fb90e4ce07e2bf96)

### ISSUE THREAD

**Issue by SDUBZ** [asiekierka/CharsetMC#120]
[02:27:57] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Illegal group reference: group index is missing
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: Illegal group reference: group index is missing
	at java.util.regex.Matcher.appendReplacement(Unknown Source) ~[?:1.8.0_121]
	at java.util.regex.Matcher.replaceFirst(Unknown Source) ~[?:1.8.0_121]
	at java.lang.String.replaceFirst(Unknown Source) ~[?:1.8.0_121]
	at pl.asie.charset.drama.DramaGenerator.applyReplacements(DramaGenerator.java:202) ~[DramaGenerator.class:?]
	at pl.asie.charset.drama.DramaGenerator.generateDrama(DramaGenerator.java:186) ~[DramaGenerator.class:?]
	at pl.asie.charset.drama.ItemDramaInABottle.func_77659_a(ItemDramaInABottle.java:38) ~[ItemDramaInABottle.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:196) ~[afj.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:359) ~[lz.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:709) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jn.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jn.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by SDUBZ** [comment]
also pipes dont interact with shifters  when trying to insert into barrels

**Comment by SDUBZ** [comment]
pipes seem broken O_O 

![2017-02-12_02 53 28] (https://cloud.githubusercontent.com/assets/14084377/22855141/eaf1d780-f0ce-11e6-8bbd-9c687d21ba5f.png)

**Comment by asiekierka** [comment]
The pipes aren't broken, they just aren't magical.

Here, have a guide: https://www.youtube.com/watch?v=RQvtJNcs1Vs

They should be redesigned fairly soon, however, so do please watch out for that change. Might make them a bit more intuitive. Or not.
