### ISSUE TITLE
Crash when placing charset pipe [1.10.2]

### ISSUE THREAD

**Issue by mattmoss** [asiekierka/CharsetMC#159]
I placed a charset pipe next to a Refined Storage network receiver and two laser relays from Actually Additions (one item, one fluid).  My intent was *not* to attach to them, just pass between them. The charset pipe appeared to attach to the network receiver and the fluid laser relay, but then crashed FTB Minecraft.

Restarting FTB Minecraft immediately crashes. I suspect I need to fix the level with MCEdit at this point.

Full log: http://paste.feed-the-beast.com/view/f2e0786f
Exception below from line 26526 of the full log.

```
[11:11:24] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering Block Entity
        at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:154) ~[bqf.class:?]
        at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125) ~[bqf.class:?]
        at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701) ~[boh.class:?]
        at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315) ~[bnz.class:?]
        at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229) ~[bnz.class:?]
        at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038) ~[bnz.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) ~[bcx.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
        at pl.asie.charset.pipes.pipe.SpecialRendererPipe.renderMultipartFast(SpecialRendererPipe.java:263) ~[SpecialRendererPipe.class:?]
        at pl.asie.charset.pipes.pipe.SpecialRendererPipe.renderMultipartFast(SpecialRendererPipe.java:52) ~[SpecialRendererPipe.class:?]
        at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerFast(MultipartContainerSpecialRenderer.java:105) ~[MultipartContainerSpecialRenderer.class:?]
        at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityFast(MultipartContainerSpecialRenderer.java:209) ~[MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.class:?]
        at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityFast(MultipartContainerSpecialRenderer.java:197) ~[MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.class:?]
        at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:144) ~[bqf.class:?]
        ... 14 more
[11:11:24] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----
 
WARNING: coremods are present:
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.1.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  literalascension (literalascension-1.10.2-1.0.2.2.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  AppleCore (AppleCore-mc1.10.2-2.2.2.jar)
  llibrary (llibrary-1.7.7-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.9.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.2.24.jar)
  HammerCoreCore (HammerCore-1.10.2-1.9.4.3.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.11.127-universal.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.3.239.jar)
Contact their authors BEFORE contacting forge
 
// My bad.
 
Time: 9/20/17 11:11 AM
Description: Rendering Block Entity
 
java.lang.NullPointerException: Rendering Block Entity
        at pl.asie.charset.pipes.pipe.SpecialRendererPipe.renderMultipartFast(SpecialRendererPipe.java:263)
        at pl.asie.charset.pipes.pipe.SpecialRendererPipe.renderMultipartFast(SpecialRendererPipe.java:52)
        at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerFast(MultipartContainerSpecialRenderer.java:105)
        at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityFast(MultipartContainerSpecialRenderer.java:209)
        at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityFast(MultipartContainerSpecialRenderer.java:197)
        at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:144)
        at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
        at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
        at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
        at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
        at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
        at net.minecraft.client.main.Main.main(SourceFile:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by mattmoss** [comment]
BTW, the mod version of charset listed in my modpack (SF3) is:  Charset-mc1.10.2-0.3.5-fd38f2c944396214

**Comment by asiekierka** [comment]
That's the newest version. Huh.

**Comment by asiekierka** [comment]
http://asie.pl/files/Charset-0.3.6-test1.jar

Keep in mind you'll need to use _modules.cfg to disable the modules not in SF3 in this version. It might fix it, however.

**Comment by asiekierka** [comment]
@mattmoss Does the linked build fix it?

**Comment by mattmoss** [comment]
Sorry, have not had a chance to test it yet. Will try to do that later today.

**Comment by mattmoss** [comment]
Yes, that seems to have resolved the crash issue. Was able to place the pipe and remove it without crashes.

Interestingly, a bit of the pipe filled with xp fluid (coming from the attached fluid laser relay). See: https://imgur.com/a/85uZL

Not an issue, since I've already routed the pipes elsewhere now.

**Comment by asiekierka** [comment]
Okay, great, thanks!

**Comment by asiekierka** [comment]
(Also, that is rather interesting, but 1.10.2 Charset is generally not supported anymore beyond crash fixes.)
