### ISSUE TITLE
Barrels cause world to crash when emptied then filled

### ISSUE THREAD

**Issue by Miaourt** [asiekierka/CharsetMC#229]
Happend  on Charset-0.5.0.244-full.jar
Hi, when we empty barrels and fill them back, we got this kind of error :

```[12:33:47] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
        at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel.lambda$info$0(TileEntityDayBarrel.java:986) ~[TileEntityDayBarrel.class:?]
        at pl.asie.charset.lib.notify.Notice.<init>(Notice.java:112) ~[Notice.class:?]
        at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel.info(TileEntityDayBarrel.java:968) ~[TileEntityDayBarrel.class:?]
        at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel.activate(TileEntityDayBarrel.java:817) ~[TileEntityDayBarrel.class:?]
        at pl.asie.charset.module.storage.barrels.BlockBarrel.func_180639_a(BlockBarrel.java:215) ~[BlockBarrel.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:446) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
        at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel.lambda$info$0(TileEntityDayBarrel.java:986) ~[TileEntityDayBarrel.class:?]
        at pl.asie.charset.lib.notify.Notice.<init>(Notice.java:112) ~[Notice.class:?]
        at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel.info(TileEntityDayBarrel.java:968) ~[TileEntityDayBarrel.class:?]
        at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel.activate(TileEntityDayBarrel.java:817) ~[TileEntityDayBarrel.class:?]
        at pl.asie.charset.module.storage.barrels.BlockBarrel.func_180639_a(BlockBarrel.java:215) ~[BlockBarrel.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:446) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.NullPointerException
```
And this crash report : 
```Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel.lambda$info$0(TileEntityDayBarrel.java:986)
	at pl.asie.charset.lib.notify.Notice.updateNotice(Notice.java:290)
	at pl.asie.charset.lib.notify.NotifyImplementation.updateRecuringNotifications(NotifyImplementation.java:140)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_112_NotifyImplementation_updateRecuringNotifications_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
```
Hope it can help, if you need any more info tell me o/

**Comment by Miaourt** [comment]
👍
