### ISSUE TITLE
Server crash when putting a iron ingot inside a storage drawer with charset immersion

### ISSUE THREAD

**Issue by Alessandro404** [asiekierka/CharsetMC#239]
Minecraft with forge 1.12.2-14.23.3.2655
Charset-Immersion-0.5.0.248a
Charset-Lib-0.5.0.248c

Thats happen only when playing in multiplayer. No problems in sp worlds. 
I can replicate the crash every time i try to do that action.

[crash-2018-06-14_16.23.22-server.txt](https://github.com/CharsetMC/Charset/files/2102702/crash-2018-06-14_16.23.22-server.txt)

**Comment by asiekierka** [comment]
Does this happen with only Minecraft, Charset and StorageDrawers?

**Comment by Alessandro404** [comment]
It does not crash, but throw a lot of errors in the server log. 

Maybe Other mods play a role here, will try with other "fix vanilla" mods to check what triggers te crash tho.

[11:23:50] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@4704de86:
java.lang.NoClassDefFoundError: net/minecraft/client/particle/ParticleManager
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_171]
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_171]
        at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:1.8.0_171]
        at pl.asie.charset.lib.utils.MethodHandleHelper.reflectMethodRecurse(MethodHandleHelper.java:43) ~[MethodHandleHelper.class:?]
        at pl.asie.charset.module.immersion.stacks.CharsetImmersionStacks.lambda$onRightClickBlock$0(CharsetImmersionStacks.java:104) ~[CharsetImmersionStacks.class:?]
        at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_171]
        at pl.asie.charset.module.immersion.stacks.CharsetImmersionStacks.onRightClickBlock(CharsetImmersionStacks.java:102) ~[CharsetImmersionStacks.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_CharsetImmersionStacks_onRightClickBlock_RightClickBlock.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1125) [ForgeHooks.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:433) [or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.ParticleManager
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
        ... 24 more
[11:23:50] [Server thread/ERROR] [FML]: Index: 4 Listeners:
[11:23:50] [Server thread/ERROR] [FML]: 0: NORMAL
[11:23:50] [Server thread/ERROR] [FML]: 1: ASM: pl.asie.charset.lib.handlers.DyeableItemWashHandler@4e956828 onBlockInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:23:50] [Server thread/ERROR] [FML]: 2: ASM: com.jaquadro.minecraft.storagedrawers.core.CommonProxy@17cff771 playerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:23:50] [Server thread/ERROR] [FML]: 3: LOWEST
[11:23:50] [Server thread/ERROR] [FML]: 4: ASM: pl.asie.charset.module.immersion.stacks.CharsetImmersionStacks@27a8002 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[11:23:50] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/particle/ParticleManager
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/ParticleManager
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_171]
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_171]
        at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:1.8.0_171]
        at pl.asie.charset.lib.utils.MethodHandleHelper.reflectMethodRecurse(MethodHandleHelper.java:43) ~[MethodHandleHelper.class:?]
        at pl.asie.charset.module.immersion.stacks.CharsetImmersionStacks.lambda$onRightClickBlock$0(CharsetImmersionStacks.java:104) ~[CharsetImmersionStacks.class:?]
        at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_171]
        at pl.asie.charset.module.immersion.stacks.CharsetImmersionStacks.onRightClickBlock(CharsetImmersionStacks.java:102) ~[CharsetImmersionStacks.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_CharsetImmersionStacks_onRightClickBlock_RightClickBlock.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1125) ~[ForgeHooks.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:433) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.ParticleManager
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_171]
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_171]
        at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:1.8.0_171]
        at pl.asie.charset.lib.utils.MethodHandleHelper.reflectMethodRecurse(MethodHandleHelper.java:43) ~[MethodHandleHelper.class:?]
        at pl.asie.charset.module.immersion.stacks.CharsetImmersionStacks.lambda$onRightClickBlock$0(CharsetImmersionStacks.java:104) ~[CharsetImmersionStacks.class:?]
        at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_171]
        at pl.asie.charset.module.immersion.stacks.CharsetImmersionStacks.onRightClickBlock(CharsetImmersionStacks.java:102) ~[CharsetImmersionStacks.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_CharsetImmersionStacks_onRightClickBlock_RightClickBlock.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1125) ~[ForgeHooks.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:433) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
>

**Comment by asiekierka** [comment]
That's a more workable bug report.

**Comment by asiekierka** [comment]
(Also, note it's probably my fault. I'll only have time to research this next week, however...)

**Comment by asiekierka** [comment]
Fixed in 0.5.0.248d.
