### ISSUE TITLE
Fails to load simplelogic:gatedefs/base.json, then NPEs

### ISSUE THREAD

**Issue by Fuyukai** [asiekierka/CharsetMC#247]
```
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: java.io.FileNotFoundException: simplelogic:gatedefs/base.json
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:69)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at pl.asie.simplelogic.gates.render.GateRenderDefinitions.load(GateRenderDefinitions.java:155)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at pl.asie.simplelogic.gates.ProxyClient.onTextureStitch(ProxyClient.java:81)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_333_ProxyClient_onTextureStitch_Pre.invoke(.dynamic)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:183)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:87)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3927)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[21:33:34] [main/INFO] [STDERR]: [pl.asie.simplelogic.gates.render.GateRenderDefinitions:load:158]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[21:33:34] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.TextureStitchEvent$Pre@77e574f:
java.lang.NullPointerException: null
	at pl.asie.simplelogic.gates.ProxyClient.onTextureStitch(ProxyClient.java:89) ~[ProxyClient.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_333_ProxyClient_onTextureStitch_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:183) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.loadSprites(TextureMap.java:87) [cdp.class:?]
	at net.minecraftforge.client.model.ModelLoader.setupModelRegistry(ModelLoader.java:161) [ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:28) [cgc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121) [cev.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:512) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3927) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

Note: This was using the latest downloads from http://charset.asie.pl/download/.

```
$ ls -l SimpleLogic-0.5.1.2.jar Charset-0.5.1.2.jar 
.rw-r--r--@ 1.9M laura 13 Jul  7:40 Charset-0.5.1.2.jar
.rw-r--r--@ 177k laura 13 Jul  7:40 SimpleLogic-0.5.1.2.jar
```

**Comment by Fuyukai** [comment]
Notably, the file does exist in the jar.

```
$ unzip -l SimpleLogic-0.5.1.2.jar  | grep -i gatedefs/base.json
      333  2018-07-13 01:33   assets/simplelogic/gatedefs/base.json
```

**Comment by asiekierka** [comment]
Ah, yes. I didn't hit that in testing, but apparently that *does* happen.

**Comment by asiekierka** [comment]
https://asie.pl/files/mods/Charset/Charset-0.5.1.2-fixed.jar

A stop-gap fixed version of Charset has been uploaded. The issue was that CF releases now put assets/simplelogic in the Charset .JAR, whereas the DDL release didn't - this wasn't a problem until 0.5.1.0. The assets will probably be split between .JARs in 1.13.
