### ISSUE TITLE
Crash on load with Ore Stone Variants after recent update

### ISSUE THREAD

**Issue by PaperTriangle** [asiekierka/CharsetMC#250]
After the 0.5.2.1 update to Charset, Minecraft fails to launch while the Chests or Dyeable Minecarts module is enabled and Ore Stone Variants is an included mod. Seems to be about resource packs. 

Since both mods show up in the crash report, I'll report to both mod authors.

Here's the crash report:
```
[21:01:11] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.4-125.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 7/20/18 9:01 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ore Stone Variants (ore_stone_variants)
Caused by: java.lang.NullPointerException
	at pl.asie.charset.lib.resources.CharsetFakeResourcePack.invalidate(CharsetFakeResourcePack.java:107)
	at pl.asie.charset.lib.resources.CharsetFakeResourcePack.func_110549_a(CharsetFakeResourcePack.java:101)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:814)
	at personthecat.mod.util.handlers.RegistryHandler.onRegisterNewResourcesBadly(RegistryHandler.java:69)
	at personthecat.mod.objects.model.ModelEventHandler.createAndRegisterResourcePack(ModelEventHandler.java:46)
	at personthecat.mod.proxy.ClientProxy.createAndRegisterResourcePack(ClientProxy.java:19)
	at personthecat.mod.Main.preInit(Main.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 356750632 bytes (340 MB) / 728760320 bytes (695 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version      | Source                                  | Signature                                |
	|:----- |:------------------ |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft          | 1.12.2       | minecraft.jar                           | None                                     |
	| UCH   | mcp                | 9.42         | minecraft.jar                           | None                                     |
	| UCH   | FML                | 8.0.99.99    | forge-1.12.2-14.23.4.2705-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge              | 14.23.4.2705 | forge-1.12.2-14.23.4.2705-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | quark              | r1.4-125     | Quark-r1.4-125.jar                      | None                                     |
	| UCH   | autoreglib         | 1.3-18       | AutoRegLib-1.3-18.jar                   | None                                     |
	| UCH   | charset            | 0.5.2.1      | Charset-0.5.2.1.jar                     | None                                     |
	| UCH   | mcmultipart        | 2.5.1        | MCMultiPart-2.5.1.jar                   | None                                     |
	| UCEE  | ore_stone_variants | 3.5          | ore_stone_variants-3.5.jar              | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.4-125.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.77' Renderer: 'GeForce GTX 660/PCIe/SSE2'
```

**Comment by asiekierka** [comment]
Nope, my fault. Downgrade to 0.5.2.0 for now.

**Comment by PaperTriangle** [comment]
Okay! Thanks for the timely response. I'll downgrade for now and close this issue.

**Comment by PaperTriangle** [comment]
I realise I read this in my incredibly tired state as "Not my fault." last night! Sorry for closing this. <_<

**Comment by asiekierka** [comment]
But I had fixed it since then, so it's fine!

**Comment by xkforce** [comment]
https://paste.ee/p/IziCN

It's back in 0.5.2.2

**Comment by asiekierka** [comment]
>  Charset-Lib-0.5.2.1

No. No, it's not.
