### ISSUE TITLE
Crashing when loading

### ISSUE THREAD

**Issue by blackstormlab** [asiekierka/CharsetMC#371]
Hello, whenever I load up the pack I'm working on it crashes when it starts to load.
----------------------------------------------------------------------------------------------------------------------
Full crash log
--------------
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 1/3/19 12:08 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Charset (charset)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Channel name already used: chrs:wires
	at pl.asie.charset.lib.loader.ModuleLoader.lambda$readDataTable$3(ModuleLoader.java:462)
	at pl.asie.charset.lib.loader.ModuleLoader$$Lambda$114/1559125071.accept(Unknown Source)
	at pl.asie.charset.lib.loader.ModuleLoader.iterateModules(ModuleLoader.java:137)
	at pl.asie.charset.lib.loader.ModuleLoader.readDataTable(ModuleLoader.java:455)
	at pl.asie.charset.lib.loader.ModuleLoader.preInit(ModuleLoader.java:588)
	at pl.asie.charset.ModCharset.preInit(ModCharset.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: Channel name already used: chrs:wires
	at pl.asie.charset.lib.network.PacketRegistry.<init>(PacketRegistry.java:57)
	at pl.asie.charset.lib.loader.ModuleLoader.lambda$readDataTable$3(ModuleLoader.java:460)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 539762328 bytes (514 MB) / 939524096 bytes (896 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 Optifine OptiFine_1.12.2_HD_U_E3 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version                  | Source                                | Signature                                |
	|:----- |:------------------ |:------------------------ |:------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft          | 1.12.2                   | minecraft.jar                         | None                                     |
	| LCH   | mcp                | 9.42                     | minecraft.jar                         | None                                     |
	| LCH   | FML                | 8.0.99.99                | forge-1.12.2-14.23.5.2796.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge              | 14.23.5.2796             | forge-1.12.2-14.23.5.2796.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | openmodscore       | 0.11.5                   | minecraft.jar                         | None                                     |
	| LCH   | bno                | 1.12.2-1.0.4.0           | Basic-Nether-Ores-Mod-1.12.2.jar      | None                                     |
	| LCH   | bonsaitrees        | 1.1.2                    | Bonsai-Trees-Mod-1.12.2.jar           | None                                     |
	| LCE   | charset            | 0.5.5.6                  | Charset-0.5.5.6.jar                   | None                                     |
	| LC    | chesttransporter   | 2.8.8                    | Chest-Transporter-Mod-1.12.2.jar      | None                                     |
	| LC    | codechickenlib     | 3.2.2.353                | CodeChickenLib-1.12.2.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | chickenchunks      | 2.4.1.73                 | ChickenChunks-Mod-1.12.2.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | chiselsandbits     | 14.22                    | Chisels-and-Bits-Mod-1.12.2.jar       | None                                     |
	| LC    | coloredredstone    | 1.0.0                    | Colored-Redstone-Mod-1.12.2.jar       | None                                     |
	| LC    | coralreef          | 2.0                      | CoralReef-Mod-1.12.2.jar              | None                                     |
	| LC    | deconstruction     | 3.0.3                    | Deconstruction-Table-Mod-1.12.2.jar   | None                                     |
	| LC    | enchxchg           | 1.0.2                    | Enchantments-Exchanger-Mod-1.12.2.jar | None                                     |
	| LC    | energyconverters   | 1.1.0.7                  | Energy-Converters-Mod-1.12.2.jar      | None                                     |
	| LC    | extrautils2        | 1.0                      | Extra-Utilities-Mod-1.12.2.jar        | None                                     |
	| LC    | fancylamps         | 1.0.2                    | Fancy-Lamps-Mod-1.12.2.jar            | None                                     |
	| LC    | harvestcraft       | 1.12.2zb                 | HarvestCraft-Mod-1.12.2.jar           | None                                     |
	| LC    | humans             | 0.1.1                    | Humans-Mod-1.12.2.jar                 | None                                     |
	| LC    | inventorytweaks    | 1.63+release.109.220f184 | Inventory-Tweaks-Mod-1.12.2.jar       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | jei                | 4.13.1.225               | jei_1.12.2-4.13.1.225.jar             | None                                     |
	| LC    | journeymap         | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar           | None                                     |
	| LC    | linear             | 1.1.1                    | Linear-Mod-1.12.2.jar                 | None                                     |
	| LC    | maille             | 2.0                      | Maille-Mod-1.12.2.jar                 | None                                     |
	| LC    | malisiscore        | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar          | None                                     |
	| LC    | malisisdoors       | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar         | None                                     |
	| LC    | mcmultipart        | 2.5.0                    | MCMultiPart-Mod-1.12.2.jar            | None                                     |
	| LC    | forgelin           | 1.5.1                    | Shadowfacts-Forgelin-1.12.2.jar       | None                                     |
	| LC    | moarboats          | 3.0.0.2                  | Moar-Boats-Mod-1.12.2.jar             | None                                     |
	| LC    | cfm                | 6.2.0                    | MrCrayfishs-Furniture-Mod-1.12.2.jar  | None                                     |
	| LC    | biomesyougo        | 1.4.0                    | Oh-The-Biomes-Youll-Go-Mod-1.12.2.jar | None                                     |
	| LC    | openmods           | 0.11.5                   | OpenModsLib-1.12.2-0.11.5.jar         | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | openblocks         | 1.7.6                    | OpenBlocks-1.12.2-1.7.6.jar           | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | ore_reeds          | 1.12.2-1.0.3             | Ore-Reeds-Mod-1.12.2.jar              | None                                     |
	| LC    | powerinventory     | 2.3.1                    | Overpowered-Inventory-Mod-1.12.1.jar  | None                                     |
	| LC    | qsilkspawners      | 1.0.0                    | Q-Silk-Spawners-Mod-1.12.2.jar        | None                                     |
	| LC    | railcraft          | 12.0.0-beta-2            | Railcraft-Mod-1.12.2.jar              | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | row                | 1.12.2-1812-4o           | Rails-of-War-Mod-1.12.2.jar           | None                                     |
	| LC    | realdrops          | 1.2.13                   | Realistic-Item-Drops-Mod-1.12.2.jar   | None                                     |
	| LC    | modroadworksreborn | 0.0.1                    | Roadworks-Reborn-Mod-1.12.2.jar       | None                                     |
	| LC    | roost              | 1.2.0                    | Roost-Mod-1.12.2.jar                  | None                                     |
	| LC    | sandyores1122      | 1.2.0                    | Sandy-Ores-Mod-1.12.2.jar             | None                                     |
	| LC    | spawnercraft       | 4.0.0                    | SpawnerCraft-Mod-1.12.2.jar           | None                                     |
	| LC    | stackable          | 1.2.0                    | Stackable-Mod-1.12.2.jar              | None                                     |
	| LC    | uteamcore          | 2.0.2.86                 | U-Team-Core-1.12.2.jar                | None                                     |
	| LC    | usefulrailroads    | 0.1.0.2-SNAPSHOT         | Useful-Railroads-Mod-1.12.2.jar       | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  
Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  invtweaks.forge.asm.ContainerTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.22' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-Renewed-1.0.0.zip
	OpenGlVersion: 4.6.0 NVIDIA 417.22
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by asiekierka** [comment]
You probably have SimpleLogic Wires installed twice. Don't use repost sites!
