### ISSUE TITLE
Crashing During Preinitialization

### ISSUE THREAD

**Issue by 4498Lincoln** [asiekierka/CharsetMC#391]
Crash Report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  CamPatchingLoader (Mine-Camera-Mod-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  weaponlib (mw-1.11.6_mc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 4/11/19 9:00 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Charset (charset)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/reflect/Field;
	at pl.asie.charset.lib.loader.ModuleLoader.passEventWithProgress(ModuleLoader.java:564)
	at pl.asie.charset.ModCharset.preInit(ModCharset.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/reflect/Field;
	at pl.asie.charset.lib.CharsetLib.preInitClient(CharsetLib.java:137)
	at pl.asie.charset.lib.loader.ModuleLoader.passEventWithProgress(ModuleLoader.java:561)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 465927920 bytes (444 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                | Source                                                 | Signature                                |
	|:----- |:-------------------- |:---------------------- |:------------------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2                 | minecraft.jar                                          | None                                     |
	| UCH   | mcp                  | 9.42                   | minecraft.jar                                          | None                                     |
	| UCH   | FML                  | 8.0.99.99              | forge-1.12.2-14.23.5.2772.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.5.2772           | forge-1.12.2-14.23.5.2772.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | MineCameraDummy      | 1.0.0                  | minecraft.jar                                          | None                                     |
	| UCH   | obfuscate            | 0.2.6                  | minecraft.jar                                          | None                                     |
	| UCH   | securitycraft        | v1.8.12                | [1.12.2]+SecurityCraft+v1.8.12.jar                     | None                                     |
	| UCH   | act                  | 2.1                    | ACT-2.1.jar                                            | None                                     |
	| UCH   | architect            | 1.2.0.6                | Architect-MC1.12-1.2.0.6.jar                           | None                                     |
	| UCEE  | charset              | 0.5.5.7                | Charset-Lib-0.5.5.7.jar                                | None                                     |
	| UC    | jei                  | 4.12.0.216             | jei_1.12.2-4.11.0.212.jar                              | None                                     |
	| UC    | betterstorage        | 3.0.0.2                | BetterStorageToo-1.12.2-3.0.0.2.jar                    | None                                     |
	| UC    | bibliocraft          | 2.4.5                  | BiblioCraft[v2.4.5][MC1.12.2].jar                      | None                                     |
	| UC    | codechickenlib       | 3.2.2.353              | CodeChickenLib-1.12.2.jar                              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | cookingforblockheads | 6.4.44                 | Cooking-for-Blockheads-Mod-1.12.2.jar                  | None                                     |
	| UC    | cdm                  | 0.4.1                  | device-mod-0.4.1-1.12.2.jar                            | None                                     |
	| UC    | forestry             | 5.8.2.356              | forestry_1.12.2-5.8.2.356.jar                          | None                                     |
	| UC    | harvestcraft         | 1.12.2w                | HarvestCraft-Mod-1.12.2.jar                            | None                                     |
	| UC    | jukebox              | 1.2                    | Jukebox-Mod-1.12.jar                                   | None                                     |
	| UC    | malisiscore          | 1.12.2-6.5.1-SNAPSHOT  | malisiscore-1.12.2-6.5.1.jar                           | None                                     |
	| UC    | malisisdoors         | 1.12.2-7.3.0           | malisisdoors-1.12.2-7.3.0.jar                          | None                                     |
	| UC    | malisisswitches      | 1.12.2-5.1.0           | malisisswitches-1.12.2-5.1.0.jar                       | None                                     |
	| UC    | mcmultipart          | 2.5.0                  | MCMultiPart-Mod-1.12.2.jar                             | None                                     |
	| UC    | mekanism             | 9.4.2                  | Mekanism-Mod-Core-1.12.2.jar                           | None                                     |
	| UC    | mekanismgenerators   | 9.4.2                  | Mekanism-Mod-Generators-1.12.2.jar                     | None                                     |
	| UC    | mekanismtools        | 9.4.2                  | Mekanism-Mod-Tools-1.12.2.jar                          | None                                     |
	| UC    | minecamera           | 1.1.1                  | Mine-Camera-Mod-1.12.2.jar                             | None                                     |
	| UC    | cfm                  | 5.13.0                 | MrCrayfishs-Furniture-Mod-1.12.2.jar                   | None                                     |
	| UC    | mw                   | 1.11.6                 | mw-1.11.6_mc1.12.2.jar                                 | None                                     |
	| UC    | currency             | 3.1.5                  | NeverEnoughCurrency-4.0.1.jar                          | None                                     |
	| UC    | nifty                | 1.16                   | NiftyBlocks-Mod-1.12.2.jar                             | None                                     |
	| UC    | ptrmodellib          | 1.0.2                  | PTRLib-1.12.2.jar                                      | None                                     |
	| UC    | reborncore           | 3.10.2.337             | RebornCore-1.12.2-3.10.2.337-universal.jar             | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UC    | redstonepaste        | 1.7.5                  | redstonepaste-mc1.12-1.7.5.jar                         | None                                     |
	| UC    | sanlib               | 1.5.0                  | SanLib-1.12.2-1.5.0.jar                                | None                                     |
	| UC    | sanplayermodel       | 1.1.1                  | SanLib-1.12.2-1.5.0.jar                                | None                                     |
	| UC    | torohealthmod        | 1.12.2-11              | torohealth-1.12.2-11.jar                               | None                                     |
	| UC    | vehicle              | 0.37.0                 | vehicle-mod-0.37.0-1.12.2.jar                          | None                                     |
	| UC    | worldedit            | 6.1.8                  | worldedit-forge-mc1.12-6.1.8-dist.jar                  | None                                     |
	| UC    | drplibrary           | 1.12.2-0.1.3-pre       | drplibrary-1.12.2-0.1.2.4-SNAPSHOT-20181115.022433.jar | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UC    | drpcmblueprints      | 1.12.2-1.2.3           | drpcmblueprints-1.12.2-1.2.3.jar                       | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UC    | drpcmmaarg           | 1.12.2-0.10.0-SNAPSHOT | drpcmmaarg-1.12.2-0.10.0-SNAPSHOT-20181116.044036.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UC    | drpcmguis            | 1.12.2-0.0.2-SNAPSHOT  | drpcmguis-1.12.2-0.0.1-SNAPSHOT-20181125.090253.jar    | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UC    | drpcore              | 1.12.2-0.4.6.2         | drpcore-1.12.2-0.4.6.2.jar                             | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UC    | drpmedieval          | 1.12.2-0.2.8-pre1      | drpmedieval-1.12.2-0.2.8-pre1.jar                      | None                                     |
	| UC    | immersiveengineering | 0.12-89                | ImmersiveEngineering-0.12-89.jar                       | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
CamPatchingLoader (Mine-Camera-Mod-1.12.2.jar)
  com.porpit.minecamera.transform.CamTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
weaponlib (mw-1.11.6_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 630'

I am using the latest (I think) version of Charset from curseforge. I don't know if I installed the wrong file if Charset has different files for different modules or anything like that, though.

**Comment by 4498Lincoln** [comment]
Mods I have:
![image](https://user-images.githubusercontent.com/49529648/55972810-119e7780-5c39-11e9-98a1-04cec18561ec.png)

**Comment by asiekierka** [comment]
Those two SimpleLogics sure don't seem like they are from CurseForge; also try updating Forge.

**Comment by 4498Lincoln** [comment]
Doesn't work with curseforge version too, updating forge to the latest version crashes my game because of my MW mod. I'll try.

**Comment by 4498Lincoln** [comment]
I got charset fixed but not Simple Logic wire and gates. I'll have to post another issue on those mods.
