### ISSUE TITLE
[Storage - Barrels] Client crash with Cyclic item cables

### ISSUE THREAD

**Issue by Cynosphere** [asiekierka/CharsetMC#440]
Version 0.5.6.4, Minecraft 1.12.2

```
java.lang.ClassCastException: net.minecraft.client.multiplayer.WorldClient cannot be cast to net.minecraft.world.WorldServer
    at pl.asie.charset.lib.network.PacketRegistry.sendToWatching(PacketRegistry.java:84)
    at pl.asie.charset.lib.network.PacketRegistry.sendToWatching(PacketRegistry.java:98)
    at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel.updateCountClients(TileEntityDayBarrel.java:711)
    at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel.sync(TileEntityDayBarrel.java:737)
    at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel.onItemChange(TileEntityDayBarrel.java:408)
    at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel.extractItem(TileEntityDayBarrel.java:521)
    at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel.access$100(TileEntityDayBarrel.java:70)
    at pl.asie.charset.module.storage.barrels.TileEntityDayBarrel$ExtractionHandler.extractItem(TileEntityDayBarrel.java:209)
    at com.lothrazar.cyclicmagic.block.cablepump.item.TileEntityItemPump.tryImport(TileEntityItemPump.java:221)
    at com.lothrazar.cyclicmagic.block.cablepump.item.TileEntityItemPump.update(TileEntityItemPump.java:154)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zbo000(World.java:4137)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by asiekierka** [comment]
Cyclic is calling a server-side-only method on the client. This is most likely a bug in Cyclic, not Charset.

**Comment by asiekierka** [comment]
Either way, I could not reproduce this specific crash, and `at net.minecraft.world.World.redirect$tileEntityUpdate$zbo000(World.java:4137)` makes me curious if some other mods were involved in the crash.
