### ISSUE TITLE
Can't Import Files

### ISSUE THREAD

**Issue by Jemmysponz** [asiekierka/CharsetMC#444]
no gui appears and this error message appears in the console:

[22:01:04] [Thread-31/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: paulscode/sound/codecs/CodecIBXM
[22:01:04] [Thread-31/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.AudioRecordThread.getCodec(AudioRecordThread.java:80)
[22:01:04] [Thread-31/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.AudioRecordThread.addIfCodec(AudioRecordThread.java:46)
[22:01:04] [Thread-31/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.AudioRecordThread.getSupportedExtensionList(AudioRecordThread.java:54)
[22:01:04] [Thread-31/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.AudioRecordThread.getSupportedExtensions(AudioRecordThread.java:41)
[22:01:04] [Thread-31/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.GuiRecordPlayer$DialogThread.run(GuiRecordPlayer.java:48)
[22:01:04] [Thread-31/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)

**Comment by asiekierka** [comment]
Something's wrong with your Forge installation - [CodecIBXM should be bundled by it.](https://github.com/MinecraftForge/MinecraftForge/tree/1.12.x/src/main/java/paulscode/sound/codecs)

**Comment by Jemmysponz** [comment]
Oh weird, it is in my forge jar but the problem is persisting.  My apologies.  It may be some other mod interfering then, I'll have to do some more digging.

**Comment by asiekierka** [comment]
The bug was specific to Forge 2851+, and is now fixed.
