### ISSUE TITLE
Server crash NoSuchMethodError: net.minecraft.util.SoundEvent.func_187503

### ISSUE THREAD

**Issue by ProsperCraft** [asiekierka/CharsetMC#85]
https://gist.github.com/ProsperCraft/fb6c1ef1fd4d5603186c5a763ab9055e

No idea what the players were doing, nobody would fess up.

Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraft.util.SoundEvent.func_187503_a()Lnet/minecraft/util/ResourceLocation;
	at pl.asie.charset.audio.note.NoteBlockManager.onNoteEvent(NoteBlockManager.java:67)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_478_NoteBlockManager_onNoteEvent_Play.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:125)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:94)
	at net.minecraft.block.BlockNote.func_189539_a(BlockNote.java:111)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:458)
	at org.spongepowered.common.event.tracking.TrackingUtil.fireMinecraftBlockEvent(TrackingUtil.java:314)
	at net.minecraft.world.WorldServer.redirect$onFireBlockEvent$zjl000(WorldServer.java:768)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1217)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:233)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/ba07181bd1e3b1c4bd571215cd417845

This is still happening with CharsetLib{0.3.0-pre15}

Does this include the patch?

**Comment by asiekierka** [comment]
You need a newer version of Charset from http://charset.asie.pl, such as 0.3.1+. Vazkii's fork is not entirely official and it is no longer maintained.
